#!/bin/bash

set -e

echo "Installing artillery for load tests: https://artillery.io/docs/getting-started/"

npm install -g npm
npm install -g artillery --unsafe-perm=true --allow-root 

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export NEXT_APP_URL=http://$NEXT_APP_COLOR-$PWS_APP_SUFFIX.$PWS_APP_DOMAIN/

echo "Running artillery load tests..."

artillery quick --duration 25 --rate 100 $NEXT_APP_URL
