---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "carbon"

inputs:
- name: concourse-pipeline-samples
- name: current-app-info

run:
  path: concourse-pipeline-samples/pipelines/appdev/blue-green-app-deployment/ci/tasks/load-tests
